FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY services/<SERVICE_NAME>/package*.json ./services/<SERVICE_NAME>/

RUN npm ci

COPY services/<SERVICE_NAME> ./services/<SERVICE_NAME>

CMD ["npm", "run", "go", "-w", "services/<SERVICE_NAME>"]