FROM node:22-alpine

WORKDIR /app/services/<SERVICE_NAME>

COPY services/<SERVICE_NAME>/package*.json ./
COPY services/<SERVICE_NAME>/tsconfig.json ./
COPY services/<SERVICE_NAME>/prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY services/<SERVICE_NAME>/src ./src
COPY services/<SERVICE_NAME>/. .

CMD ["npm", "run", "go"]