services:
  <SERVICE_NAME>:
    build:
      context: ../
      dockerfile: services/<SERVICE_NAME>/dockerfile
    env_file:
      - .env
      - .env.prod
    ports:
      - '${SERVICE_PORT}:${SERVICE_PORT}'
    networks: [app-network]

networks:
  app-network:
    external: true
    name: qucore_<MODULE_NAME>_network
