services:
  <SERVICE_NAME>:
    build:
      context: ../
      dockerfile: services/<SERVICE_NAME>/dockerfile
    volumes:
      - ../services/<SERVICE_NAME>/src:/app/services/<SERVICE_NAME>/src
      - ../services/<SERVICE_NAME>/package.json:/app/services/<SERVICE_NAME>/package.json
      - ../services/<SERVICE_NAME>/package-lock.json:/app/services/<SERVICE_NAME>/package-lock.json
    command: npm run dev # Use dev for hot-reloading during development
    ports:
      - '${SERVICE_PORT}:${SERVICE_PORT}'
    env_file:
      - .env
    networks: [app-network]

networks:
  app-network:
    external: true
    name: qucore_<MODULE>_network
