services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env.prod
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: always
    env_file:
      - .env.prod
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    name: qucore_<MODULE_NAME>_network
