services:
  <SERVICE_NAME>:
    build:
      context: .
      dockerfile: services/<SERVICE_NAME>/dockerfile
    volumes:
      - ./services/<SERVICE_NAME>:/app/services/<SERVICE_NAME>
      - ./packages/qucore-common:/app/packages/qucore-common
      - /app/node_modules
      - /app/dist
    command: npm run dev -w services/<SERVICE_NAME> # Use dev for hot-reloading during development
    env_file:
      - .env
      - .env.prod
    ports:
      - '${SERVICE_PORT}:${SERVICE_PORT}'
    networks: [app-network]

networks:
  app-network:
    external: true
    name: qucore_<MODULE_NAME>_network
