name: Fullstack Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Lint check
        run: npm run lint

      # - name: Prisma Generate
      #   run: npm run prisma:generate --workspaces --if-present

      # - name: Build Backend & Services
      #   run: npm run build --workspace=server --workspaces --if-present

      # - name: Build Frontend
      #   run: npm run build --workspace=client

      # - name: Run All Tests
      #   run: npm run test --workspaces --if-present
